upstream fastcgi_backend {
    server 127.0.0.1:9000;
}

server {
    listen 8080;
    server_name localhost;

    # 1. Definir la variable raíz indispensable para Magento
    set $MAGE_ROOT /var/www/html;

    # 2. Rutas temporales obligatorias para correr sin privilegios root (GKE)
    client_body_temp_path /tmp/nginx_client_body;
    proxy_temp_path       /tmp/nginx_proxy;
    fastcgi_temp_path     /tmp/nginx_fastcgi;

    # 3. Incluir el archivo oficial (él se encarga de index, autoindex, root, etc.)
    include /var/www/html/nginx.conf.sample;
}
